#!/usr/bin/with-contenv bash
set -e

DATA_DIR="/config/data"

# Create new folder for data
if [ ! -d "$DATA_DIR" ]; then
    echo "[hassio] Creating folder ${DATA_DIR} for add-on data"
    mkdir -p $DATA_DIR
fi
