#!/usr/bin/with-contenv bash

if [[ $(jq -r '.disable_ipfs' /data/options.json) == true ]]; then
  echo "[svc-ipfs] IPFS disabled in Home Assistant configuration"
  rm --rf /data/.ipfs
  sleep infinity
fi

HOME=/data exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 4001" \
        s6-setuidgid abc ipfs daemon
