#!/usr/bin/with-contenv bash
# shellcheck shell=bash

DISABLE_IPFS=$(jq -r '.disable_ipfs' /data/options.json)

if [[ "${DISABLE_IPFS}" == true ]]; then
    echo "[svc-ipfs] IPFS disabled in Home Assistant configuration"
    rm -rf /data/.ipfs
    sleep infinity
else
    HOME=/data exec \
        s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 4001" \
        s6-setuidgid abc ipfs daemon
fi
